version: '3'
services:
  # postgres teste
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root      
    ports:
      - "5434:5432"
    volumes:
      - ./shared/db/migration_docker_test.sql:/docker-entrypoint-initdb.d/migration_docker_test.sql   